# --------Importing Data--------
data = read.csv("Attrdata.csv")

# -----Splitting Data------
set.seed(123)
d = sort(sample(nrow(data), nrow(data) * .7))

#select training and test sample
train <- data[d, ]
test <- data[-d, ]

names(train)
Ind_Var = colnames(train)[3:ncol(train)]
final <- matrix(NA, 2, 5)
# -----Bivariate-----
for (i in 3:ncol(train)) {
  v1 = glm(Response ~ train[, i], data = train, family = binomial)
  s1 <- summary.glm(v1)$coefficients
  category <- as.data.frame(rep((Ind_Var)[i - 2], nrow(s1)))
  summary <- cbind(category, s1)
  names(summary)[1] = paste("Variable")
  final <- rbind(as.matrix(summary), final)
}

write.csv(final, file = "Bivariate.csv")
# ----Correlation Matrix-------
cor_matrix = cor(train)
write.csv(cor_matrix, file = "cor.csv")

# -----VIF------
install.packages("car")
library(car)
# Step-1
model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_09_099 + COMP_RATIO_LT_08 +
    COUNTRY_INDIA + COUNTRY_OTHERS + COUNTRY_US + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    NO_OF_SUPV_CHG_GRP_LT_3 + NO_OF_SUPV_CHG_GRP_UNKNOWN + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED +
    REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG + REVIEW_RTG_NOT_RATED +
    REVIEW_RTG_OUTSTANDING + REVIEW_RTG_STRONG + TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA +
    WORK_SITE_BNG + WORK_SITE_SANJOSE + WORK_STATE_CALIFORNIA + WORK_STATE_KARNATAKA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_LT_3 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_GE_3 +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
vif(model_vif)
# Error in vif.default(model_vif) :
# Identifying alias coefficients:
alias(model_vif)


# Step-1 (after eliminating alias coeficients)
model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_09_099 + COMP_RATIO_LT_08 +
    COUNTRY_INDIA + COUNTRY_OTHERS + COUNTRY_US + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    REVIEW_RTG_LTR_STRONG + TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA + WORK_SITE_SANJOSE +
    WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL +
    YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_LT_3 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_GE_3 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif1.csv")
# Step-2 (after eliminating alias coeficients)
model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_09_099 + COMP_RATIO_LT_08 +
    COUNTRY_INDIA + COUNTRY_OTHERS + COUNTRY_US + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    REVIEW_RTG_LTR_STRONG + TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA + WORK_SITE_SANJOSE +
    WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL +
    YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_LT_3 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif2.csv")
# Step-3 (after eliminating COMP_RATIO_09_099)
model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + COUNTRY_US + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_SITE_SANJOSE + WORK_STATE_CALIFORNIA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_LT_3 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif3.csv")


# Step-4 (after eliminating YRS_SINCE_LAST_PROMO_LT_3)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + COUNTRY_US + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_SITE_SANJOSE + WORK_STATE_CALIFORNIA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif4.csv")

# Step-5 (after eliminating COUNTRY_US)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_SITE_SANJOSE + WORK_STATE_CALIFORNIA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_2_3999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif5.csv")


# Step-6 (after eliminating WORK_SITE_SANJOSE)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER +
    WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_2_3999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 +
    YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif6.csv")

# Step-7 (after eliminating YRS_GRADE_RANGE_2_3999)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_2014_UNKNOWN + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + REVIEW_RTG_LTR_STRONG +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER +
    WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_1_1999 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif7.csv")


# Step-8 (after eliminating NO_OF_SUPV_CHG_2014_UNKNOWN)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    REVIEW_RTG_LTR_STRONG + TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 +
    YRS_IN_JOB_RANGE_1_1999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif8.csv")


# Step-9 (after eliminating YRS_IN_JOB_RANGE_1_1999)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    REVIEW_RTG_LTR_STRONG + TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif9.csv")


# Step-10 (after eliminating REVIEW_RTG_LTR_STRONG)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_INDIA +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER +
    WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif10.csv")

# Step-11 (after eliminating COUNTRY_INDIA)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_015 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS +
    ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 +
    GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER +
    LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U +
    MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER +
    WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif11.csv")

# Step-12 (after eliminating BONUS_015)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 +
    COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    TOTAL_PROMO_UNKNOWN + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER +
    WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif12.csv")

# Step-13 (after eliminating TOTAL_PROMO_UNKNOWN)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 +
    COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA +
    WORK_STATE_CALIFORNIA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL +
    YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_GRADE_RANGE_LT_1 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif13.csv")

# Step-14 (after eliminating WORK_STATE_CALIFORNIA)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_008 + BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 +
    COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif14.csv")


# Step-15 (after eliminating BONUS_008 )

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 +
    COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_GRADE_RANGE_LT_1 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif15.csv")



# Step-16 (after eliminating YRS_GRADE_RANGE_LT_1)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_36_40 + AGE_41_45 + AGE_46_50 + AGE_GT_50 +
    BONUS_GTE_025 + BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 +
    COMP_RATIO_08_089 + COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_APJC + WORK_REGION_EMEA +
    WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif16.csv")


# Step-17 (after eliminating AGE_36_40)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_APJC + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL +
    YRS_GRADE_RANGE_1_1999 + YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif17.csv")

# Step-18 (after eliminating WORK_REGION_APJC)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_1_1999 +
    YRS_GRADE_RANGE_4_5999 + YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif18.csv")

# Step-19 (after eliminating YRS_GRADE_RANGE_1_1999)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + NO_OF_SUPV_CHG_GRP_LT_3 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif19.csv")

# Step-20 (after eliminating NO_OF_SUPV_CHG_GRP_LT_3)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_4_5999 +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif20.csv")

# Step-21 (after eliminating YRS_GRADE_RANGE_4_5999)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + WORK_TYPE_TRADITIONAL + YRS_GRADE_RANGE_6_9999 +
    YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 +
    YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 +
    YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif21.csv")


# Step-22 (after eliminating WORK_TYPE_TRADITIONAL)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_GTE_025 +
    BONUS_LTE_007 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 +
    COMP_RATIO_LT_08 + COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN +
    GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 +
    GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC +
    MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif22.csv")

# Step-23 (after eliminating BONUS_GTE_025)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    COUNTRY_OTHERS + ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M +
    GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 +
    JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S +
    MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING +
    TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA +
    WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 +
    YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 +
    YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 +
    YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 +
    YRS_SINCE_LAST_PROMO_OTHERS + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif23.csv")


# Step-24 (after eliminating COUNTRY_OTHERS)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 +
    GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER +
    LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U +
    MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_PROMO_OTHERS +
    YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif24.csv")

# Step-25 (after eliminating YRS_SINCE_LAST_PROMO_OTHERS)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 +
    GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER +
    LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U +
    MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_NOT_RATED + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif25.csv")

# Step-26 (after eliminating REVIEW_RTG_LTR_NOT_RATED)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_4 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 +
    GRADE_GRP_11 + GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER +
    LOA_DAYS_GRP_UNKNOWN + MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U +
    MARITAL_STATUS_UNKNOWN + MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 +
    NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 +
    ORG_NAME_ENG + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif26.csv")

# Step-27 (after eliminating ETHNIC_GRP_4)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 +
    GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_ENG + ORG_NAME_SALES +
    ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif27.csv")



# Step-28 (after eliminating ORG_NAME_ENG)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 +
    GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_6_9999 + YRS_IN_SERVICE_RANGE_GTE_15 +
    YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif28.csv")


# Step-29 (after eliminating YRS_IN_SERVICE_RANGE_6_9999)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + BONUS_LTE_007 +
    COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 +
    ETHNIC_GRP_1 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 +
    GRADE_GRP_12 + GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif29.csv")

# Step-30 (after eliminating BONUS_LTE_007)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + ETHNIC_GRP_1 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MILITARY_STATUS_NOT_VETERAN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 +
    NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV +
    REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 +
    WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif30.csv")

# Step-31 (after eliminating MILITARY_STATUS_NOT_VETERAN)

model_vif = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + ETHNIC_GRP_1 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s <- vif(model_vif)
write.csv(s, file = "vif31.csv")


# -----Stepwise Selection----
install.packages("stats")
library(stats)
model_test = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + COMP_RATION_1_119 +
    COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + ETHNIC_GRP_1 +
    ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_12 +
    GRADE_GRP_1_5 + GRADE_GRP_6_7 + JOBTITLE_GRP_OTHER + LOA_DAYS_GRP_UNKNOWN +
    MANAGER_LEVEL_IC + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN +
    MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 +
    NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL +
    REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG +
    WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER +
    YRS_GRADE_RANGE_6_9999 + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 +
    YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 +
    YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 +
    YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
model_step = step(model_test)
s = summary(model_step)
write.csv(s$coefficients, file = "stepwise.csv")

# -----Final Model---------
model_final = glm(
  Response ~ AGE_25_30 + AGE_31_35 + AGE_41_45 + AGE_46_50 + AGE_GT_50 + COMP_RATION_1_119 + COMP_RATION_GT_119 + COMP_RATIO_08_089 + COMP_RATIO_LT_08 + ETHNIC_GRP_1 + ETHNIC_GRP_UNKNOWN + GENDER_M + GRADE_GRP_10 + GRADE_GRP_11 + GRADE_GRP_1_5 + JOBTITLE_GRP_OTHER + MARITAL_STATUS_S + MARITAL_STATUS_U + MARITAL_STATUS_UNKNOWN + MNG_LOC_LOC + NO_OF_SUPV_CHG_2014_LT_3 + NO_OF_SUPV_CHG_GRP_3_5 + NO_OF_SUPV_CHG_GRP_6_7 + NO_OF_SUPV_CHG_GRP_8_10 + ORG_NAME_SALES + ORG_NAME_SERV + REVIEW_RTG_EXCEPTIONAL + REVIEW_RTG_LTR_OUTSTANDING + TOTAL_PROMO_GRP_LT_3 + WORK_LOCATION_BNG + WORK_LOCATION_US_CALIFORNIA + WORK_REGION_EMEA + WORK_TYPE_MOBILE_WORKER + YRS_IN_JOB_RANGE_2_3999 + YRS_IN_JOB_RANGE_4_5999 + YRS_IN_JOB_RANGE_LT_1 + YRS_IN_SERVICE_RANGE_10_14999 + YRS_IN_SERVICE_RANGE_1_1999 + YRS_IN_SERVICE_RANGE_2_3999 + YRS_IN_SERVICE_RANGE_GTE_15 + YRS_IN_SERVICE_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + YRS_SINCE_LAST_SAL_CHG_LT_3,
  data = train,
  family = binomial
)
s1 <- summary.glm(model_final)$coefficients
write.csv(s1, file = "final_coff.csv")


# --------Concordance and Discordance----------
OptimisedConc = function(model)
{
  Data = cbind(model$y, model$fitted.values)
  ones = Data[Data[, 1] == 1, ]
  zeros = Data[Data[, 1] == 0, ]
  conc = matrix(0, dim(zeros)[1], dim(ones)[1])
  disc = matrix(0, dim(zeros)[1], dim(ones)[1])
  ties = matrix(0, dim(zeros)[1], dim(ones)[1])
  for (j in 1:dim(zeros)[1])
  {
    for (i in 1:dim(ones)[1])
    {
      if (ones[i, 2] > zeros[j, 2])
      {
        conc[j, i] = 1
      }
      else if (ones[i, 2] < zeros[j, 2])
      {
        disc[j, i] = 1
      }
      else if (ones[i, 2] == zeros[j, 2])
      {
        ties[j, i] = 1
      }
    }
  }
  Pairs = dim(zeros)[1] * dim(ones)[1]
  PercentConcordance = (sum(conc) / Pairs) * 100
  PercentDiscordance = (sum(disc) / Pairs) * 100
  PercentTied = (sum(ties) / Pairs) * 100
  return(
    list(
      "Percent Concordance" = PercentConcordance,
      "Percent Discordance" = PercentDiscordance,
      "Percent Tied" = PercentTied,
      "Pairs" = Pairs
    )
  )
}

OptimisedConc(model_step)

# -----fitted values------
train$predicted = predict(model_final, train, type = "response")
write.csv(train, file = "data_fitted.csv")



# ROC Curve
install.packages("pROC")
library(pROC)
plot(
  roc(train$Response, train$predicted, direction = "<"),
  col = "red",
  lwd = 3,
  main = "The turtle finds its way"
)

# --------same model running on validation sample--------------
modle_final_test = glm(
  Response ~ YRS_IN_JOB_RANGE_LT_1 + YRS_SINCE_LAST_PROMO_3_499 + AGE_GT_50 +
    WORK_LOCATION_US_CALIFORNIA + AGE_46_50 + YRS_IN_JOB_RANGE_4_5999 + YRS_SINCE_LAST_SAL_CHG_LT_3 +
    COMP_RATIO_LT_08 + YRS_IN_SERVICE_RANGE_GTE_15 + AGE_41_45 + YRS_IN_JOB_RANGE_2_3999 +
    COMP_RATION_GT_119 + WORK_TYPE_MOBILE_WORKER + GRADE_GRP_10 + YRS_IN_SERVICE_RANGE_10_14999,
  data = test,
  family = binomial
)
summary(modle_final_test)

# --------Concordance and Discordance----------
OptimisedConc = function(model)
{
  Data = cbind(model$y, model$fitted.values)
  ones = Data[Data[, 1] == 1, ]
  zeros = Data[Data[, 1] == 0, ]
  conc = matrix(0, dim(zeros)[1], dim(ones)[1])
  disc = matrix(0, dim(zeros)[1], dim(ones)[1])
  ties = matrix(0, dim(zeros)[1], dim(ones)[1])
  for (j in 1:dim(zeros)[1])
  {
    for (i in 1:dim(ones)[1])
    {
      if (ones[i, 2] > zeros[j, 2])
      {
        conc[j, i] = 1
      }
      else if (ones[i, 2] < zeros[j, 2])
      {
        disc[j, i] = 1
      }
      else if (ones[i, 2] == zeros[j, 2])
      {
        ties[j, i] = 1
      }
    }
  }
  Pairs = dim(zeros)[1] * dim(ones)[1]
  PercentConcordance = (sum(conc) / Pairs) * 100
  PercentDiscordance = (sum(disc) / Pairs) * 100
  PercentTied = (sum(ties) / Pairs) * 100
  return(
    list(
      "Percent Concordance" = PercentConcordance,
      "Percent Discordance" = PercentDiscordance,
      "Percent Tied" = PercentTied,
      "Pairs" = Pairs
    )
  )
}

OptimisedConc(modle_final_test)


# -----fitted values------
test$predicted = predict(modle_final_test, test, type = "response")
write.csv(test, file = "data_fitted_test.csv")

# ROC Curve
plot(
  roc(test$Response, test$predicted, direction = "<"),
  col = "red",
  lwd = 3,
  main = "The turtle finds its way"
)

# ----Scores Generation-------------------------
score = read.csv("active.csv")

score$predicted = predict(model_final, score, type = "response")

write.csv(score, file = "scores.csv")
